language: minimal
sudo: false
os: linux

branches:
    only:
        - master

jobs:
  fast_finish: true
  include:
    - env:
        PYTHON=2.7
    - env:
        PYTHON=3.5
    - env:
        PYTHON=3.6

install:
  - source testing/install_conda.sh
  - conda create -n testenv python=$PYTHON pytest flake8 virtualenv -y
  - source activate testenv
  - pip install .
  - pip list
  - ./testing/setup_envs.sh

script:
  - source activate testenv
  - py.test venv_pack --runslow -s -vv
  - flake8 venv_pack

notifications:
  email: false
